package com.dunbian.jujiabao.appobj.generator;

import java.math.BigDecimal;
import java.util.Date;

public class Discount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.id
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.name
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.type
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.discount_amount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private BigDecimal discountAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.discount_rate
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Integer discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.grade_min
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Integer gradeMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.grade_max
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Integer gradeMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.region
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.region_name
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.consume_min
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private BigDecimal consumeMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.consume_max
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private BigDecimal consumeMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.start_date
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.end_date
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.limit
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Integer limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.join
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Integer join;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.use_mix
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private String useMix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.user_limit
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Integer userLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.status
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.create_time
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discount.for_new
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    private String forNew;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.id
     *
     * @return the value of t_discount.id
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.id
     *
     * @param id the value for t_discount.id
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.name
     *
     * @return the value of t_discount.name
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.name
     *
     * @param name the value for t_discount.name
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.type
     *
     * @return the value of t_discount.type
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.type
     *
     * @param type the value for t_discount.type
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.discount_amount
     *
     * @return the value of t_discount.discount_amount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.discount_amount
     *
     * @param discountAmount the value for t_discount.discount_amount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.discount_rate
     *
     * @return the value of t_discount.discount_rate
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Integer getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.discount_rate
     *
     * @param discountRate the value for t_discount.discount_rate
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setDiscountRate(Integer discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.grade_min
     *
     * @return the value of t_discount.grade_min
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Integer getGradeMin() {
        return gradeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.grade_min
     *
     * @param gradeMin the value for t_discount.grade_min
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setGradeMin(Integer gradeMin) {
        this.gradeMin = gradeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.grade_max
     *
     * @return the value of t_discount.grade_max
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Integer getGradeMax() {
        return gradeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.grade_max
     *
     * @param gradeMax the value for t_discount.grade_max
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setGradeMax(Integer gradeMax) {
        this.gradeMax = gradeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.region
     *
     * @return the value of t_discount.region
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.region
     *
     * @param region the value for t_discount.region
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.region_name
     *
     * @return the value of t_discount.region_name
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.region_name
     *
     * @param regionName the value for t_discount.region_name
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.consume_min
     *
     * @return the value of t_discount.consume_min
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public BigDecimal getConsumeMin() {
        return consumeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.consume_min
     *
     * @param consumeMin the value for t_discount.consume_min
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setConsumeMin(BigDecimal consumeMin) {
        this.consumeMin = consumeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.consume_max
     *
     * @return the value of t_discount.consume_max
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public BigDecimal getConsumeMax() {
        return consumeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.consume_max
     *
     * @param consumeMax the value for t_discount.consume_max
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setConsumeMax(BigDecimal consumeMax) {
        this.consumeMax = consumeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.start_date
     *
     * @return the value of t_discount.start_date
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.start_date
     *
     * @param startDate the value for t_discount.start_date
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.end_date
     *
     * @return the value of t_discount.end_date
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.end_date
     *
     * @param endDate the value for t_discount.end_date
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.limit
     *
     * @return the value of t_discount.limit
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.limit
     *
     * @param limit the value for t_discount.limit
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.join
     *
     * @return the value of t_discount.join
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Integer getJoin() {
        return join;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.join
     *
     * @param join the value for t_discount.join
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setJoin(Integer join) {
        this.join = join;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.use_mix
     *
     * @return the value of t_discount.use_mix
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getUseMix() {
        return useMix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.use_mix
     *
     * @param useMix the value for t_discount.use_mix
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setUseMix(String useMix) {
        this.useMix = useMix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.user_limit
     *
     * @return the value of t_discount.user_limit
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Integer getUserLimit() {
        return userLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.user_limit
     *
     * @param userLimit the value for t_discount.user_limit
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setUserLimit(Integer userLimit) {
        this.userLimit = userLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.status
     *
     * @return the value of t_discount.status
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.status
     *
     * @param status the value for t_discount.status
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.create_time
     *
     * @return the value of t_discount.create_time
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.create_time
     *
     * @param createTime the value for t_discount.create_time
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discount.for_new
     *
     * @return the value of t_discount.for_new
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getForNew() {
        return forNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discount.for_new
     *
     * @param forNew the value for t_discount.for_new
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setForNew(String forNew) {
        this.forNew = forNew;
    }
}