package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.FoodDetail;
import com.dunbian.jujiabao.appobj.extend.FoodDetailAO;
import com.dunbian.jujiabao.appobj.generator.FoodDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int countByExample(FoodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int deleteByExample(FoodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int insert(FoodDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int insertSelective(FoodDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    List<FoodDetailAO> selectByExample(FoodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
	FoodDetailAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") FoodDetail record, @Param("example") FoodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByExample(@Param("record") FoodDetail record, @Param("example") FoodDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByPrimaryKeySelective(FoodDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByPrimaryKey(FoodDetail record);
}
