package com.dunbian.jujiabao.appobj.generator;

import java.util.Date;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.user_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_type
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.file_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.file_path
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.file_name
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.data_type
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.data_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.sort
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.status
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.create_time
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.id
     *
     * @return the value of t_resource.id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.id
     *
     * @param id the value for t_resource.id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.user_id
     *
     * @return the value of t_resource.user_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.user_id
     *
     * @param userId the value for t_resource.user_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_type
     *
     * @return the value of t_resource.resource_type
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_type
     *
     * @param resourceType the value for t_resource.resource_type
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.file_id
     *
     * @return the value of t_resource.file_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.file_id
     *
     * @param fileId the value for t_resource.file_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.file_path
     *
     * @return the value of t_resource.file_path
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.file_path
     *
     * @param filePath the value for t_resource.file_path
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.file_name
     *
     * @return the value of t_resource.file_name
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.file_name
     *
     * @param fileName the value for t_resource.file_name
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.data_type
     *
     * @return the value of t_resource.data_type
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.data_type
     *
     * @param dataType the value for t_resource.data_type
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.data_id
     *
     * @return the value of t_resource.data_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.data_id
     *
     * @param dataId the value for t_resource.data_id
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.sort
     *
     * @return the value of t_resource.sort
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.sort
     *
     * @param sort the value for t_resource.sort
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.status
     *
     * @return the value of t_resource.status
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.status
     *
     * @param status the value for t_resource.status
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.create_time
     *
     * @return the value of t_resource.create_time
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.create_time
     *
     * @param createTime the value for t_resource.create_time
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}