package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.FoodSet;
import com.dunbian.jujiabao.appobj.extend.FoodSetAO;
import com.dunbian.jujiabao.appobj.generator.FoodSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int countByExample(FoodSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int deleteByExample(FoodSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int insert(FoodSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int insertSelective(FoodSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    List<FoodSetAO> selectByExample(FoodSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
	FoodSetAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") FoodSet record, @Param("example") FoodSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByExample(@Param("record") FoodSet record, @Param("example") FoodSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByPrimaryKeySelective(FoodSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_set
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByPrimaryKey(FoodSet record);
}
