package com.dunbian.jujiabao.appobj.generator;

import java.util.Date;

public class FoodWeek {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.id
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.day
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.set_id
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private String setId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.set_name
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private String setName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.type
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.sort
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.create_time
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.day_count
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private Integer dayCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_week.day_sale
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    private Integer daySale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.id
     *
     * @return the value of t_food_week.id
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.id
     *
     * @param id the value for t_food_week.id
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.day
     *
     * @return the value of t_food_week.day
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.day
     *
     * @param day the value for t_food_week.day
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.set_id
     *
     * @return the value of t_food_week.set_id
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public String getSetId() {
        return setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.set_id
     *
     * @param setId the value for t_food_week.set_id
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setSetId(String setId) {
        this.setId = setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.set_name
     *
     * @return the value of t_food_week.set_name
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public String getSetName() {
        return setName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.set_name
     *
     * @param setName the value for t_food_week.set_name
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setSetName(String setName) {
        this.setName = setName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.type
     *
     * @return the value of t_food_week.type
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.type
     *
     * @param type the value for t_food_week.type
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.sort
     *
     * @return the value of t_food_week.sort
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.sort
     *
     * @param sort the value for t_food_week.sort
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.create_time
     *
     * @return the value of t_food_week.create_time
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.create_time
     *
     * @param createTime the value for t_food_week.create_time
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.day_count
     *
     * @return the value of t_food_week.day_count
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public Integer getDayCount() {
        return dayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.day_count
     *
     * @param dayCount the value for t_food_week.day_count
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setDayCount(Integer dayCount) {
        this.dayCount = dayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_week.day_sale
     *
     * @return the value of t_food_week.day_sale
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public Integer getDaySale() {
        return daySale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_week.day_sale
     *
     * @param daySale the value for t_food_week.day_sale
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    public void setDaySale(Integer daySale) {
        this.daySale = daySale;
    }
}