package com.dunbian.jujiabao.appobj.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SeckillResultExample {
	/*生成分页所需元素开始*/
	private int startRecord = -1;

	private int pageCount = -1;

	public void setStartRecord(int startRecord){
	   this.startRecord = startRecord;
	}

	public int getStartRecord(){
	   return startRecord;
	}

	public void setPageCount(int pageCount){
	   this.pageCount = pageCount;
	}

	public int getPageCount(){
	   return pageCount;
	}

	/*生成分页所需元素结束*/
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public SeckillResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andSecIdIsNull() {
            addCriterion("sec_id is null");
            return (Criteria) this;
        }

        public Criteria andSecIdIsNotNull() {
            addCriterion("sec_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecIdEqualTo(Long value) {
            addCriterion("sec_id =", value, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdNotEqualTo(Long value) {
            addCriterion("sec_id <>", value, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdGreaterThan(Long value) {
            addCriterion("sec_id >", value, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sec_id >=", value, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdLessThan(Long value) {
            addCriterion("sec_id <", value, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdLessThanOrEqualTo(Long value) {
            addCriterion("sec_id <=", value, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdIn(List<Long> values) {
            addCriterion("sec_id in", values, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdNotIn(List<Long> values) {
            addCriterion("sec_id not in", values, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdBetween(Long value1, Long value2) {
            addCriterion("sec_id between", value1, value2, "secId");
            return (Criteria) this;
        }

        public Criteria andSecIdNotBetween(Long value1, Long value2) {
            addCriterion("sec_id not between", value1, value2, "secId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdIsNull() {
            addCriterion("sec_instance_id is null");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdIsNotNull() {
            addCriterion("sec_instance_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdEqualTo(String value) {
            addCriterion("sec_instance_id =", value, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdNotEqualTo(String value) {
            addCriterion("sec_instance_id <>", value, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdGreaterThan(String value) {
            addCriterion("sec_instance_id >", value, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdGreaterThanOrEqualTo(String value) {
            addCriterion("sec_instance_id >=", value, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdLessThan(String value) {
            addCriterion("sec_instance_id <", value, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdLessThanOrEqualTo(String value) {
            addCriterion("sec_instance_id <=", value, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdIn(List<String> values) {
            addCriterion("sec_instance_id in", values, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdNotIn(List<String> values) {
            addCriterion("sec_instance_id not in", values, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdBetween(String value1, String value2) {
            addCriterion("sec_instance_id between", value1, value2, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecInstanceIdNotBetween(String value1, String value2) {
            addCriterion("sec_instance_id not between", value1, value2, "secInstanceId");
            return (Criteria) this;
        }

        public Criteria andSecTimeIsNull() {
            addCriterion("sec_time is null");
            return (Criteria) this;
        }

        public Criteria andSecTimeIsNotNull() {
            addCriterion("sec_time is not null");
            return (Criteria) this;
        }

        public Criteria andSecTimeEqualTo(Date value) {
            addCriterion("sec_time =", value, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeNotEqualTo(Date value) {
            addCriterion("sec_time <>", value, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeGreaterThan(Date value) {
            addCriterion("sec_time >", value, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sec_time >=", value, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeLessThan(Date value) {
            addCriterion("sec_time <", value, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeLessThanOrEqualTo(Date value) {
            addCriterion("sec_time <=", value, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeIn(List<Date> values) {
            addCriterion("sec_time in", values, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeNotIn(List<Date> values) {
            addCriterion("sec_time not in", values, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeBetween(Date value1, Date value2) {
            addCriterion("sec_time between", value1, value2, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecTimeNotBetween(Date value1, Date value2) {
            addCriterion("sec_time not between", value1, value2, "secTime");
            return (Criteria) this;
        }

        public Criteria andSecDateIsNull() {
            addCriterion("sec_date is null");
            return (Criteria) this;
        }

        public Criteria andSecDateIsNotNull() {
            addCriterion("sec_date is not null");
            return (Criteria) this;
        }

        public Criteria andSecDateEqualTo(Date value) {
            addCriterionForJDBCDate("sec_date =", value, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("sec_date <>", value, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateGreaterThan(Date value) {
            addCriterionForJDBCDate("sec_date >", value, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sec_date >=", value, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateLessThan(Date value) {
            addCriterionForJDBCDate("sec_date <", value, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sec_date <=", value, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateIn(List<Date> values) {
            addCriterionForJDBCDate("sec_date in", values, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("sec_date not in", values, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sec_date between", value1, value2, "secDate");
            return (Criteria) this;
        }

        public Criteria andSecDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sec_date not between", value1, value2, "secDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_seckill_result
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 25 21:56:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
