package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.RegionStatus;
import com.dunbian.jujiabao.appobj.extend.RegionStatusAO;
import com.dunbian.jujiabao.appobj.generator.RegionStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegionStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int countByExample(RegionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int deleteByExample(RegionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int insert(RegionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int insertSelective(RegionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    List<RegionStatusAO> selectByExample(RegionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
	RegionStatusAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") RegionStatus record, @Param("example") RegionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int updateByExample(@Param("record") RegionStatus record, @Param("example") RegionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int updateByPrimaryKeySelective(RegionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region_status
     *
     * @mbggenerated Fri May 08 09:53:59 CST 2015
     */
    int updateByPrimaryKey(RegionStatus record);
}
