package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.SeckillResult;
import com.dunbian.jujiabao.appobj.extend.SeckillResultAO;
import com.dunbian.jujiabao.appobj.generator.SeckillResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int countByExample(SeckillResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int deleteByExample(SeckillResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int insert(SeckillResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int insertSelective(SeckillResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    List<SeckillResultAO> selectByExample(SeckillResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
	SeckillResultAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") SeckillResult record, @Param("example") SeckillResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int updateByExample(@Param("record") SeckillResult record, @Param("example") SeckillResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int updateByPrimaryKeySelective(SeckillResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_result
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    int updateByPrimaryKey(SeckillResult record);
}
