package com.dunbian.jujiabao.appobj.generator;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SeckillExample {
	/*生成分页所需元素开始*/
	private int startRecord = -1;

	private int pageCount = -1;

	public void setStartRecord(int startRecord){
	   this.startRecord = startRecord;
	}

	public int getStartRecord(){
	   return startRecord;
	}

	public void setPageCount(int pageCount){
	   this.pageCount = pageCount;
	}

	public int getPageCount(){
	   return pageCount;
	}

	/*生成分页所需元素结束*/
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public SeckillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andShowTimeIsNull() {
            addCriterion("show_time is null");
            return (Criteria) this;
        }

        public Criteria andShowTimeIsNotNull() {
            addCriterion("show_time is not null");
            return (Criteria) this;
        }

        public Criteria andShowTimeEqualTo(Date value) {
            addCriterion("show_time =", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotEqualTo(Date value) {
            addCriterion("show_time <>", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeGreaterThan(Date value) {
            addCriterion("show_time >", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("show_time >=", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeLessThan(Date value) {
            addCriterion("show_time <", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeLessThanOrEqualTo(Date value) {
            addCriterion("show_time <=", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeIn(List<Date> values) {
            addCriterion("show_time in", values, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotIn(List<Date> values) {
            addCriterion("show_time not in", values, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeBetween(Date value1, Date value2) {
            addCriterion("show_time between", value1, value2, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotBetween(Date value1, Date value2) {
            addCriterion("show_time not between", value1, value2, "showTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeIsNull() {
            addCriterion("hidden_time is null");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeIsNotNull() {
            addCriterion("hidden_time is not null");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeEqualTo(Date value) {
            addCriterion("hidden_time =", value, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeNotEqualTo(Date value) {
            addCriterion("hidden_time <>", value, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeGreaterThan(Date value) {
            addCriterion("hidden_time >", value, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("hidden_time >=", value, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeLessThan(Date value) {
            addCriterion("hidden_time <", value, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeLessThanOrEqualTo(Date value) {
            addCriterion("hidden_time <=", value, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeIn(List<Date> values) {
            addCriterion("hidden_time in", values, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeNotIn(List<Date> values) {
            addCriterion("hidden_time not in", values, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeBetween(Date value1, Date value2) {
            addCriterion("hidden_time between", value1, value2, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andHiddenTimeNotBetween(Date value1, Date value2) {
            addCriterion("hidden_time not between", value1, value2, "hiddenTime");
            return (Criteria) this;
        }

        public Criteria andInventoryWebIsNull() {
            addCriterion("inventory_web is null");
            return (Criteria) this;
        }

        public Criteria andInventoryWebIsNotNull() {
            addCriterion("inventory_web is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryWebEqualTo(Integer value) {
            addCriterion("inventory_web =", value, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebNotEqualTo(Integer value) {
            addCriterion("inventory_web <>", value, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebGreaterThan(Integer value) {
            addCriterion("inventory_web >", value, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebGreaterThanOrEqualTo(Integer value) {
            addCriterion("inventory_web >=", value, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebLessThan(Integer value) {
            addCriterion("inventory_web <", value, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebLessThanOrEqualTo(Integer value) {
            addCriterion("inventory_web <=", value, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebIn(List<Integer> values) {
            addCriterion("inventory_web in", values, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebNotIn(List<Integer> values) {
            addCriterion("inventory_web not in", values, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebBetween(Integer value1, Integer value2) {
            addCriterion("inventory_web between", value1, value2, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryWebNotBetween(Integer value1, Integer value2) {
            addCriterion("inventory_web not between", value1, value2, "inventoryWeb");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneIsNull() {
            addCriterion("inventory_phone is null");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneIsNotNull() {
            addCriterion("inventory_phone is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneEqualTo(Integer value) {
            addCriterion("inventory_phone =", value, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneNotEqualTo(Integer value) {
            addCriterion("inventory_phone <>", value, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneGreaterThan(Integer value) {
            addCriterion("inventory_phone >", value, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("inventory_phone >=", value, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneLessThan(Integer value) {
            addCriterion("inventory_phone <", value, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("inventory_phone <=", value, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneIn(List<Integer> values) {
            addCriterion("inventory_phone in", values, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneNotIn(List<Integer> values) {
            addCriterion("inventory_phone not in", values, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneBetween(Integer value1, Integer value2) {
            addCriterion("inventory_phone between", value1, value2, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("inventory_phone not between", value1, value2, "inventoryPhone");
            return (Criteria) this;
        }

        public Criteria andInventoryShareIsNull() {
            addCriterion("inventory_share is null");
            return (Criteria) this;
        }

        public Criteria andInventoryShareIsNotNull() {
            addCriterion("inventory_share is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryShareEqualTo(Integer value) {
            addCriterion("inventory_share =", value, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareNotEqualTo(Integer value) {
            addCriterion("inventory_share <>", value, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareGreaterThan(Integer value) {
            addCriterion("inventory_share >", value, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareGreaterThanOrEqualTo(Integer value) {
            addCriterion("inventory_share >=", value, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareLessThan(Integer value) {
            addCriterion("inventory_share <", value, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareLessThanOrEqualTo(Integer value) {
            addCriterion("inventory_share <=", value, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareIn(List<Integer> values) {
            addCriterion("inventory_share in", values, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareNotIn(List<Integer> values) {
            addCriterion("inventory_share not in", values, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareBetween(Integer value1, Integer value2) {
            addCriterion("inventory_share between", value1, value2, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andInventoryShareNotBetween(Integer value1, Integer value2) {
            addCriterion("inventory_share not between", value1, value2, "inventoryShare");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andQuestionWebIsNull() {
            addCriterion("question_web is null");
            return (Criteria) this;
        }

        public Criteria andQuestionWebIsNotNull() {
            addCriterion("question_web is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionWebEqualTo(String value) {
            addCriterion("question_web =", value, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebNotEqualTo(String value) {
            addCriterion("question_web <>", value, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebGreaterThan(String value) {
            addCriterion("question_web >", value, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebGreaterThanOrEqualTo(String value) {
            addCriterion("question_web >=", value, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebLessThan(String value) {
            addCriterion("question_web <", value, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebLessThanOrEqualTo(String value) {
            addCriterion("question_web <=", value, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebLike(String value) {
            addCriterion("question_web like", value, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebNotLike(String value) {
            addCriterion("question_web not like", value, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebIn(List<String> values) {
            addCriterion("question_web in", values, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebNotIn(List<String> values) {
            addCriterion("question_web not in", values, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebBetween(String value1, String value2) {
            addCriterion("question_web between", value1, value2, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionWebNotBetween(String value1, String value2) {
            addCriterion("question_web not between", value1, value2, "questionWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebIsNull() {
            addCriterion("answer_web is null");
            return (Criteria) this;
        }

        public Criteria andAnswerWebIsNotNull() {
            addCriterion("answer_web is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerWebEqualTo(String value) {
            addCriterion("answer_web =", value, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebNotEqualTo(String value) {
            addCriterion("answer_web <>", value, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebGreaterThan(String value) {
            addCriterion("answer_web >", value, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebGreaterThanOrEqualTo(String value) {
            addCriterion("answer_web >=", value, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebLessThan(String value) {
            addCriterion("answer_web <", value, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebLessThanOrEqualTo(String value) {
            addCriterion("answer_web <=", value, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebLike(String value) {
            addCriterion("answer_web like", value, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebNotLike(String value) {
            addCriterion("answer_web not like", value, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebIn(List<String> values) {
            addCriterion("answer_web in", values, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebNotIn(List<String> values) {
            addCriterion("answer_web not in", values, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebBetween(String value1, String value2) {
            addCriterion("answer_web between", value1, value2, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andAnswerWebNotBetween(String value1, String value2) {
            addCriterion("answer_web not between", value1, value2, "answerWeb");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneIsNull() {
            addCriterion("question_phone is null");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneIsNotNull() {
            addCriterion("question_phone is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneEqualTo(String value) {
            addCriterion("question_phone =", value, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneNotEqualTo(String value) {
            addCriterion("question_phone <>", value, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneGreaterThan(String value) {
            addCriterion("question_phone >", value, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("question_phone >=", value, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneLessThan(String value) {
            addCriterion("question_phone <", value, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneLessThanOrEqualTo(String value) {
            addCriterion("question_phone <=", value, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneLike(String value) {
            addCriterion("question_phone like", value, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneNotLike(String value) {
            addCriterion("question_phone not like", value, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneIn(List<String> values) {
            addCriterion("question_phone in", values, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneNotIn(List<String> values) {
            addCriterion("question_phone not in", values, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneBetween(String value1, String value2) {
            addCriterion("question_phone between", value1, value2, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andQuestionPhoneNotBetween(String value1, String value2) {
            addCriterion("question_phone not between", value1, value2, "questionPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneIsNull() {
            addCriterion("answer_phone is null");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneIsNotNull() {
            addCriterion("answer_phone is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneEqualTo(String value) {
            addCriterion("answer_phone =", value, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneNotEqualTo(String value) {
            addCriterion("answer_phone <>", value, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneGreaterThan(String value) {
            addCriterion("answer_phone >", value, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("answer_phone >=", value, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneLessThan(String value) {
            addCriterion("answer_phone <", value, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneLessThanOrEqualTo(String value) {
            addCriterion("answer_phone <=", value, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneLike(String value) {
            addCriterion("answer_phone like", value, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneNotLike(String value) {
            addCriterion("answer_phone not like", value, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneIn(List<String> values) {
            addCriterion("answer_phone in", values, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneNotIn(List<String> values) {
            addCriterion("answer_phone not in", values, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneBetween(String value1, String value2) {
            addCriterion("answer_phone between", value1, value2, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andAnswerPhoneNotBetween(String value1, String value2) {
            addCriterion("answer_phone not between", value1, value2, "answerPhone");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNull() {
            addCriterion("region_id is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("region_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(String value) {
            addCriterion("region_id =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(String value) {
            addCriterion("region_id <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(String value) {
            addCriterion("region_id >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(String value) {
            addCriterion("region_id >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(String value) {
            addCriterion("region_id <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(String value) {
            addCriterion("region_id <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<String> values) {
            addCriterion("region_id in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<String> values) {
            addCriterion("region_id not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(String value1, String value2) {
            addCriterion("region_id between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(String value1, String value2) {
            addCriterion("region_id not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNull() {
            addCriterion("region_name is null");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNotNull() {
            addCriterion("region_name is not null");
            return (Criteria) this;
        }

        public Criteria andRegionNameEqualTo(String value) {
            addCriterion("region_name =", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotEqualTo(String value) {
            addCriterion("region_name <>", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThan(String value) {
            addCriterion("region_name >", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThanOrEqualTo(String value) {
            addCriterion("region_name >=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThan(String value) {
            addCriterion("region_name <", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThanOrEqualTo(String value) {
            addCriterion("region_name <=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLike(String value) {
            addCriterion("region_name like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotLike(String value) {
            addCriterion("region_name not like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameIn(List<String> values) {
            addCriterion("region_name in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotIn(List<String> values) {
            addCriterion("region_name not in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameBetween(String value1, String value2) {
            addCriterion("region_name between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotBetween(String value1, String value2) {
            addCriterion("region_name not between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andMdIsNull() {
            addCriterion("md is null");
            return (Criteria) this;
        }

        public Criteria andMdIsNotNull() {
            addCriterion("md is not null");
            return (Criteria) this;
        }

        public Criteria andMdEqualTo(String value) {
            addCriterion("md =", value, "md");
            return (Criteria) this;
        }

        public Criteria andMdNotEqualTo(String value) {
            addCriterion("md <>", value, "md");
            return (Criteria) this;
        }

        public Criteria andMdGreaterThan(String value) {
            addCriterion("md >", value, "md");
            return (Criteria) this;
        }

        public Criteria andMdGreaterThanOrEqualTo(String value) {
            addCriterion("md >=", value, "md");
            return (Criteria) this;
        }

        public Criteria andMdLessThan(String value) {
            addCriterion("md <", value, "md");
            return (Criteria) this;
        }

        public Criteria andMdLessThanOrEqualTo(String value) {
            addCriterion("md <=", value, "md");
            return (Criteria) this;
        }

        public Criteria andMdLike(String value) {
            addCriterion("md like", value, "md");
            return (Criteria) this;
        }

        public Criteria andMdNotLike(String value) {
            addCriterion("md not like", value, "md");
            return (Criteria) this;
        }

        public Criteria andMdIn(List<String> values) {
            addCriterion("md in", values, "md");
            return (Criteria) this;
        }

        public Criteria andMdNotIn(List<String> values) {
            addCriterion("md not in", values, "md");
            return (Criteria) this;
        }

        public Criteria andMdBetween(String value1, String value2) {
            addCriterion("md between", value1, value2, "md");
            return (Criteria) this;
        }

        public Criteria andMdNotBetween(String value1, String value2) {
            addCriterion("md not between", value1, value2, "md");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIsNull() {
            addCriterion("market_price is null");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIsNotNull() {
            addCriterion("market_price is not null");
            return (Criteria) this;
        }

        public Criteria andMarketPriceEqualTo(BigDecimal value) {
            addCriterion("market_price =", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotEqualTo(BigDecimal value) {
            addCriterion("market_price <>", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceGreaterThan(BigDecimal value) {
            addCriterion("market_price >", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("market_price >=", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceLessThan(BigDecimal value) {
            addCriterion("market_price <", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("market_price <=", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIn(List<BigDecimal> values) {
            addCriterion("market_price in", values, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotIn(List<BigDecimal> values) {
            addCriterion("market_price not in", values, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("market_price between", value1, value2, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("market_price not between", value1, value2, "marketPrice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_seckill
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 06 15:07:45 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
