package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.PayLog;
import com.dunbian.jujiabao.appobj.extend.PayLogAO;
import com.dunbian.jujiabao.appobj.generator.PayLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int countByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int deleteByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int insert(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int insertSelective(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    List<PayLogAO> selectByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
	PayLogAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") PayLog record, @Param("example") PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int updateByExample(@Param("record") PayLog record, @Param("example") PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int updateByPrimaryKeySelective(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_log
     *
     * @mbggenerated Wed Apr 15 10:35:29 CST 2015
     */
    int updateByPrimaryKey(PayLog record);
}
