package com.dunbian.jujiabao.appobj.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdvertisementExample {
	/*生成分页所需元素开始*/
	private int startRecord = -1;

	private int pageCount = -1;

	public void setStartRecord(int startRecord){
	   this.startRecord = startRecord;
	}

	public int getStartRecord(){
	   return startRecord;
	}

	public void setPageCount(int pageCount){
	   this.pageCount = pageCount;
	}

	public int getPageCount(){
	   return pageCount;
	}

	/*生成分页所需元素结束*/
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public AdvertisementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andImgWebIsNull() {
            addCriterion("img_web is null");
            return (Criteria) this;
        }

        public Criteria andImgWebIsNotNull() {
            addCriterion("img_web is not null");
            return (Criteria) this;
        }

        public Criteria andImgWebEqualTo(String value) {
            addCriterion("img_web =", value, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebNotEqualTo(String value) {
            addCriterion("img_web <>", value, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebGreaterThan(String value) {
            addCriterion("img_web >", value, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebGreaterThanOrEqualTo(String value) {
            addCriterion("img_web >=", value, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebLessThan(String value) {
            addCriterion("img_web <", value, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebLessThanOrEqualTo(String value) {
            addCriterion("img_web <=", value, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebLike(String value) {
            addCriterion("img_web like", value, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebNotLike(String value) {
            addCriterion("img_web not like", value, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebIn(List<String> values) {
            addCriterion("img_web in", values, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebNotIn(List<String> values) {
            addCriterion("img_web not in", values, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebBetween(String value1, String value2) {
            addCriterion("img_web between", value1, value2, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgWebNotBetween(String value1, String value2) {
            addCriterion("img_web not between", value1, value2, "imgWeb");
            return (Criteria) this;
        }

        public Criteria andImgPhoneIsNull() {
            addCriterion("img_phone is null");
            return (Criteria) this;
        }

        public Criteria andImgPhoneIsNotNull() {
            addCriterion("img_phone is not null");
            return (Criteria) this;
        }

        public Criteria andImgPhoneEqualTo(String value) {
            addCriterion("img_phone =", value, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneNotEqualTo(String value) {
            addCriterion("img_phone <>", value, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneGreaterThan(String value) {
            addCriterion("img_phone >", value, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("img_phone >=", value, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneLessThan(String value) {
            addCriterion("img_phone <", value, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneLessThanOrEqualTo(String value) {
            addCriterion("img_phone <=", value, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneLike(String value) {
            addCriterion("img_phone like", value, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneNotLike(String value) {
            addCriterion("img_phone not like", value, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneIn(List<String> values) {
            addCriterion("img_phone in", values, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneNotIn(List<String> values) {
            addCriterion("img_phone not in", values, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneBetween(String value1, String value2) {
            addCriterion("img_phone between", value1, value2, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andImgPhoneNotBetween(String value1, String value2) {
            addCriterion("img_phone not between", value1, value2, "imgPhone");
            return (Criteria) this;
        }

        public Criteria andActionsIsNull() {
            addCriterion("actions is null");
            return (Criteria) this;
        }

        public Criteria andActionsIsNotNull() {
            addCriterion("actions is not null");
            return (Criteria) this;
        }

        public Criteria andActionsEqualTo(String value) {
            addCriterion("actions =", value, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsNotEqualTo(String value) {
            addCriterion("actions <>", value, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsGreaterThan(String value) {
            addCriterion("actions >", value, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsGreaterThanOrEqualTo(String value) {
            addCriterion("actions >=", value, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsLessThan(String value) {
            addCriterion("actions <", value, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsLessThanOrEqualTo(String value) {
            addCriterion("actions <=", value, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsLike(String value) {
            addCriterion("actions like", value, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsNotLike(String value) {
            addCriterion("actions not like", value, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsIn(List<String> values) {
            addCriterion("actions in", values, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsNotIn(List<String> values) {
            addCriterion("actions not in", values, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsBetween(String value1, String value2) {
            addCriterion("actions between", value1, value2, "actions");
            return (Criteria) this;
        }

        public Criteria andActionsNotBetween(String value1, String value2) {
            addCriterion("actions not between", value1, value2, "actions");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBackgroundIsNull() {
            addCriterion("background is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundIsNotNull() {
            addCriterion("background is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundEqualTo(String value) {
            addCriterion("background =", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundNotEqualTo(String value) {
            addCriterion("background <>", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundGreaterThan(String value) {
            addCriterion("background >", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("background >=", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundLessThan(String value) {
            addCriterion("background <", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundLessThanOrEqualTo(String value) {
            addCriterion("background <=", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundLike(String value) {
            addCriterion("background like", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundNotLike(String value) {
            addCriterion("background not like", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundIn(List<String> values) {
            addCriterion("background in", values, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundNotIn(List<String> values) {
            addCriterion("background not in", values, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundBetween(String value1, String value2) {
            addCriterion("background between", value1, value2, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundNotBetween(String value1, String value2) {
            addCriterion("background not between", value1, value2, "background");
            return (Criteria) this;
        }

        public Criteria andSupportVersionIsNull() {
            addCriterion("support_version is null");
            return (Criteria) this;
        }

        public Criteria andSupportVersionIsNotNull() {
            addCriterion("support_version is not null");
            return (Criteria) this;
        }

        public Criteria andSupportVersionEqualTo(Integer value) {
            addCriterion("support_version =", value, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionNotEqualTo(Integer value) {
            addCriterion("support_version <>", value, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionGreaterThan(Integer value) {
            addCriterion("support_version >", value, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("support_version >=", value, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionLessThan(Integer value) {
            addCriterion("support_version <", value, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionLessThanOrEqualTo(Integer value) {
            addCriterion("support_version <=", value, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionIn(List<Integer> values) {
            addCriterion("support_version in", values, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionNotIn(List<Integer> values) {
            addCriterion("support_version not in", values, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionBetween(Integer value1, Integer value2) {
            addCriterion("support_version between", value1, value2, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andSupportVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("support_version not between", value1, value2, "supportVersion");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgIsNull() {
            addCriterion("unsupport_msg is null");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgIsNotNull() {
            addCriterion("unsupport_msg is not null");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgEqualTo(String value) {
            addCriterion("unsupport_msg =", value, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgNotEqualTo(String value) {
            addCriterion("unsupport_msg <>", value, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgGreaterThan(String value) {
            addCriterion("unsupport_msg >", value, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgGreaterThanOrEqualTo(String value) {
            addCriterion("unsupport_msg >=", value, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgLessThan(String value) {
            addCriterion("unsupport_msg <", value, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgLessThanOrEqualTo(String value) {
            addCriterion("unsupport_msg <=", value, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgLike(String value) {
            addCriterion("unsupport_msg like", value, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgNotLike(String value) {
            addCriterion("unsupport_msg not like", value, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgIn(List<String> values) {
            addCriterion("unsupport_msg in", values, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgNotIn(List<String> values) {
            addCriterion("unsupport_msg not in", values, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgBetween(String value1, String value2) {
            addCriterion("unsupport_msg between", value1, value2, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andUnsupportMsgNotBetween(String value1, String value2) {
            addCriterion("unsupport_msg not between", value1, value2, "unsupportMsg");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_advertisement
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 21 15:46:54 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_advertisement
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
