package com.dunbian.jujiabao.appobj.generator;

import java.util.Date;

public class Cart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.user_id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.set_id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    private String setId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.type
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.count
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.cart_date
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    private Date cartDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.id
     *
     * @return the value of t_cart.id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.id
     *
     * @param id the value for t_cart.id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.user_id
     *
     * @return the value of t_cart.user_id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.user_id
     *
     * @param userId the value for t_cart.user_id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.set_id
     *
     * @return the value of t_cart.set_id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public String getSetId() {
        return setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.set_id
     *
     * @param setId the value for t_cart.set_id
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public void setSetId(String setId) {
        this.setId = setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.type
     *
     * @return the value of t_cart.type
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.type
     *
     * @param type the value for t_cart.type
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.count
     *
     * @return the value of t_cart.count
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.count
     *
     * @param count the value for t_cart.count
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.cart_date
     *
     * @return the value of t_cart.cart_date
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public Date getCartDate() {
        return cartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.cart_date
     *
     * @param cartDate the value for t_cart.cart_date
     *
     * @mbggenerated Fri Apr 03 10:54:58 CST 2015
     */
    public void setCartDate(Date cartDate) {
        this.cartDate = cartDate;
    }
}