package com.dunbian.jujiabao.appobj.generator;

import java.util.Date;

public class RegionTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region_time.id
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region_time.region_id
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region_time.region_name
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region_time.type
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region_time.start_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region_time.end_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region_time.delivery_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    private String deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region_time.create_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region_time.id
     *
     * @return the value of t_region_time.id
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region_time.id
     *
     * @param id the value for t_region_time.id
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region_time.region_id
     *
     * @return the value of t_region_time.region_id
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region_time.region_id
     *
     * @param regionId the value for t_region_time.region_id
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region_time.region_name
     *
     * @return the value of t_region_time.region_name
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region_time.region_name
     *
     * @param regionName the value for t_region_time.region_name
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region_time.type
     *
     * @return the value of t_region_time.type
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region_time.type
     *
     * @param type the value for t_region_time.type
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region_time.start_time
     *
     * @return the value of t_region_time.start_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region_time.start_time
     *
     * @param startTime the value for t_region_time.start_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region_time.end_time
     *
     * @return the value of t_region_time.end_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region_time.end_time
     *
     * @param endTime the value for t_region_time.end_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region_time.delivery_time
     *
     * @return the value of t_region_time.delivery_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region_time.delivery_time
     *
     * @param deliveryTime the value for t_region_time.delivery_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region_time.create_time
     *
     * @return the value of t_region_time.create_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region_time.create_time
     *
     * @param createTime the value for t_region_time.create_time
     *
     * @mbggenerated Sat Mar 07 17:52:47 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}