package com.dunbian.jujiabao.appobj.generator;

import java.math.BigDecimal;
import java.util.Date;

public class Seckill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.id
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.name
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.memo
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.price
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.show_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private Date showTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.start_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.end_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.hidden_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private Date hiddenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.inventory_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private Integer inventoryWeb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.inventory_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private Integer inventoryPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.inventory_share
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private Integer inventoryShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.type
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.logo
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.create_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.question_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String questionWeb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.answer_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String answerWeb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.question_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String questionPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.answer_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String answerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.region_id
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.region_name
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.md
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String md;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.status
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.market_price
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    private BigDecimal marketPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.id
     *
     * @return the value of t_seckill.id
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.id
     *
     * @param id the value for t_seckill.id
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.name
     *
     * @return the value of t_seckill.name
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.name
     *
     * @param name the value for t_seckill.name
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.memo
     *
     * @return the value of t_seckill.memo
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.memo
     *
     * @param memo the value for t_seckill.memo
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.price
     *
     * @return the value of t_seckill.price
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.price
     *
     * @param price the value for t_seckill.price
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.show_time
     *
     * @return the value of t_seckill.show_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Date getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.show_time
     *
     * @param showTime the value for t_seckill.show_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.start_time
     *
     * @return the value of t_seckill.start_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.start_time
     *
     * @param startTime the value for t_seckill.start_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.end_time
     *
     * @return the value of t_seckill.end_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.end_time
     *
     * @param endTime the value for t_seckill.end_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.hidden_time
     *
     * @return the value of t_seckill.hidden_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Date getHiddenTime() {
        return hiddenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.hidden_time
     *
     * @param hiddenTime the value for t_seckill.hidden_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setHiddenTime(Date hiddenTime) {
        this.hiddenTime = hiddenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.inventory_web
     *
     * @return the value of t_seckill.inventory_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Integer getInventoryWeb() {
        return inventoryWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.inventory_web
     *
     * @param inventoryWeb the value for t_seckill.inventory_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setInventoryWeb(Integer inventoryWeb) {
        this.inventoryWeb = inventoryWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.inventory_phone
     *
     * @return the value of t_seckill.inventory_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Integer getInventoryPhone() {
        return inventoryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.inventory_phone
     *
     * @param inventoryPhone the value for t_seckill.inventory_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setInventoryPhone(Integer inventoryPhone) {
        this.inventoryPhone = inventoryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.inventory_share
     *
     * @return the value of t_seckill.inventory_share
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Integer getInventoryShare() {
        return inventoryShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.inventory_share
     *
     * @param inventoryShare the value for t_seckill.inventory_share
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setInventoryShare(Integer inventoryShare) {
        this.inventoryShare = inventoryShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.type
     *
     * @return the value of t_seckill.type
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.type
     *
     * @param type the value for t_seckill.type
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.logo
     *
     * @return the value of t_seckill.logo
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.logo
     *
     * @param logo the value for t_seckill.logo
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.create_time
     *
     * @return the value of t_seckill.create_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.create_time
     *
     * @param createTime the value for t_seckill.create_time
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.question_web
     *
     * @return the value of t_seckill.question_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getQuestionWeb() {
        return questionWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.question_web
     *
     * @param questionWeb the value for t_seckill.question_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setQuestionWeb(String questionWeb) {
        this.questionWeb = questionWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.answer_web
     *
     * @return the value of t_seckill.answer_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getAnswerWeb() {
        return answerWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.answer_web
     *
     * @param answerWeb the value for t_seckill.answer_web
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setAnswerWeb(String answerWeb) {
        this.answerWeb = answerWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.question_phone
     *
     * @return the value of t_seckill.question_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getQuestionPhone() {
        return questionPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.question_phone
     *
     * @param questionPhone the value for t_seckill.question_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setQuestionPhone(String questionPhone) {
        this.questionPhone = questionPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.answer_phone
     *
     * @return the value of t_seckill.answer_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getAnswerPhone() {
        return answerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.answer_phone
     *
     * @param answerPhone the value for t_seckill.answer_phone
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setAnswerPhone(String answerPhone) {
        this.answerPhone = answerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.region_id
     *
     * @return the value of t_seckill.region_id
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.region_id
     *
     * @param regionId the value for t_seckill.region_id
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.region_name
     *
     * @return the value of t_seckill.region_name
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.region_name
     *
     * @param regionName the value for t_seckill.region_name
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.md
     *
     * @return the value of t_seckill.md
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getMd() {
        return md;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.md
     *
     * @param md the value for t_seckill.md
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setMd(String md) {
        this.md = md;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.status
     *
     * @return the value of t_seckill.status
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.status
     *
     * @param status the value for t_seckill.status
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.market_price
     *
     * @return the value of t_seckill.market_price
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.market_price
     *
     * @param marketPrice the value for t_seckill.market_price
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }
}