package com.dunbian.jujiabao.appobj.generator;

public class SeckillInstance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_instance.id
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_instance.seckill_id
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    private String seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_instance.inventory_type
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    private String inventoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_instance.status
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_instance.id
     *
     * @return the value of t_seckill_instance.id
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_instance.id
     *
     * @param id the value for t_seckill_instance.id
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_instance.seckill_id
     *
     * @return the value of t_seckill_instance.seckill_id
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public String getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_instance.seckill_id
     *
     * @param seckillId the value for t_seckill_instance.seckill_id
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public void setSeckillId(String seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_instance.inventory_type
     *
     * @return the value of t_seckill_instance.inventory_type
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public String getInventoryType() {
        return inventoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_instance.inventory_type
     *
     * @param inventoryType the value for t_seckill_instance.inventory_type
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public void setInventoryType(String inventoryType) {
        this.inventoryType = inventoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_instance.status
     *
     * @return the value of t_seckill_instance.status
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_instance.status
     *
     * @param status the value for t_seckill_instance.status
     *
     * @mbggenerated Wed Mar 25 21:56:14 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }
}