package com.dunbian.jujiabao.appobj.generator;

import java.util.Date;

public class Advertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.id
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.name
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.img_web
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String imgWeb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.img_phone
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String imgPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.actions
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String actions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.type
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.background
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String background;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.support_version
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private Integer supportVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.unsupport_msg
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String unsupportMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.status
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.create_time
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.content
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.id
     *
     * @return the value of t_advertisement.id
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.id
     *
     * @param id the value for t_advertisement.id
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.name
     *
     * @return the value of t_advertisement.name
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.name
     *
     * @param name the value for t_advertisement.name
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.img_web
     *
     * @return the value of t_advertisement.img_web
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getImgWeb() {
        return imgWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.img_web
     *
     * @param imgWeb the value for t_advertisement.img_web
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setImgWeb(String imgWeb) {
        this.imgWeb = imgWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.img_phone
     *
     * @return the value of t_advertisement.img_phone
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getImgPhone() {
        return imgPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.img_phone
     *
     * @param imgPhone the value for t_advertisement.img_phone
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setImgPhone(String imgPhone) {
        this.imgPhone = imgPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.actions
     *
     * @return the value of t_advertisement.actions
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getActions() {
        return actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.actions
     *
     * @param actions the value for t_advertisement.actions
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setActions(String actions) {
        this.actions = actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.type
     *
     * @return the value of t_advertisement.type
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.type
     *
     * @param type the value for t_advertisement.type
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.background
     *
     * @return the value of t_advertisement.background
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getBackground() {
        return background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.background
     *
     * @param background the value for t_advertisement.background
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setBackground(String background) {
        this.background = background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.support_version
     *
     * @return the value of t_advertisement.support_version
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public Integer getSupportVersion() {
        return supportVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.support_version
     *
     * @param supportVersion the value for t_advertisement.support_version
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setSupportVersion(Integer supportVersion) {
        this.supportVersion = supportVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.unsupport_msg
     *
     * @return the value of t_advertisement.unsupport_msg
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getUnsupportMsg() {
        return unsupportMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.unsupport_msg
     *
     * @param unsupportMsg the value for t_advertisement.unsupport_msg
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setUnsupportMsg(String unsupportMsg) {
        this.unsupportMsg = unsupportMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.status
     *
     * @return the value of t_advertisement.status
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.status
     *
     * @param status the value for t_advertisement.status
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.create_time
     *
     * @return the value of t_advertisement.create_time
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.create_time
     *
     * @param createTime the value for t_advertisement.create_time
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.content
     *
     * @return the value of t_advertisement.content
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.content
     *
     * @param content the value for t_advertisement.content
     *
     * @mbggenerated Sat Mar 21 15:46:54 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}