package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.OrderExtra;
import com.dunbian.jujiabao.appobj.extend.OrderExtraAO;
import com.dunbian.jujiabao.appobj.generator.OrderExtraExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int countByExample(OrderExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int deleteByExample(OrderExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int insert(OrderExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int insertSelective(OrderExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    List<OrderExtraAO> selectByExample(OrderExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
	OrderExtraAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrderExtra record, @Param("example") OrderExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByExample(@Param("record") OrderExtra record, @Param("example") OrderExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByPrimaryKeySelective(OrderExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_extra
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByPrimaryKey(OrderExtra record);
}
