package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.UserWallet;
import com.dunbian.jujiabao.appobj.extend.UserWalletAO;
import com.dunbian.jujiabao.appobj.generator.UserWalletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int countByExample(UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int deleteByExample(UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int insert(UserWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int insertSelective(UserWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    List<UserWalletAO> selectByExample(UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
	UserWalletAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserWallet record, @Param("example") UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int updateByExample(@Param("record") UserWallet record, @Param("example") UserWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int updateByPrimaryKeySelective(UserWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wallet
     *
     * @mbggenerated Tue Apr 14 16:54:51 CST 2015
     */
    int updateByPrimaryKey(UserWallet record);
}
