package com.dunbian.jujiabao.appobj.generator;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DiscountExample {
	/*生成分页所需元素开始*/
	private int startRecord = -1;

	private int pageCount = -1;

	public void setStartRecord(int startRecord){
	   this.startRecord = startRecord;
	}

	public int getStartRecord(){
	   return startRecord;
	}

	public void setPageCount(int pageCount){
	   this.pageCount = pageCount;
	}

	public int getPageCount(){
	   return pageCount;
	}

	/*生成分页所需元素结束*/
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public DiscountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountIsNull() {
            addCriterion("discount_amount is null");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountIsNotNull() {
            addCriterion("discount_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountEqualTo(BigDecimal value) {
            addCriterion("discount_amount =", value, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountNotEqualTo(BigDecimal value) {
            addCriterion("discount_amount <>", value, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountGreaterThan(BigDecimal value) {
            addCriterion("discount_amount >", value, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_amount >=", value, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountLessThan(BigDecimal value) {
            addCriterion("discount_amount <", value, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_amount <=", value, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountIn(List<BigDecimal> values) {
            addCriterion("discount_amount in", values, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountNotIn(List<BigDecimal> values) {
            addCriterion("discount_amount not in", values, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_amount between", value1, value2, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_amount not between", value1, value2, "discountAmount");
            return (Criteria) this;
        }

        public Criteria andDiscountRateIsNull() {
            addCriterion("discount_rate is null");
            return (Criteria) this;
        }

        public Criteria andDiscountRateIsNotNull() {
            addCriterion("discount_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountRateEqualTo(Integer value) {
            addCriterion("discount_rate =", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateNotEqualTo(Integer value) {
            addCriterion("discount_rate <>", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateGreaterThan(Integer value) {
            addCriterion("discount_rate >", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("discount_rate >=", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateLessThan(Integer value) {
            addCriterion("discount_rate <", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateLessThanOrEqualTo(Integer value) {
            addCriterion("discount_rate <=", value, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateIn(List<Integer> values) {
            addCriterion("discount_rate in", values, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateNotIn(List<Integer> values) {
            addCriterion("discount_rate not in", values, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateBetween(Integer value1, Integer value2) {
            addCriterion("discount_rate between", value1, value2, "discountRate");
            return (Criteria) this;
        }

        public Criteria andDiscountRateNotBetween(Integer value1, Integer value2) {
            addCriterion("discount_rate not between", value1, value2, "discountRate");
            return (Criteria) this;
        }

        public Criteria andGradeMinIsNull() {
            addCriterion("grade_min is null");
            return (Criteria) this;
        }

        public Criteria andGradeMinIsNotNull() {
            addCriterion("grade_min is not null");
            return (Criteria) this;
        }

        public Criteria andGradeMinEqualTo(Integer value) {
            addCriterion("grade_min =", value, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinNotEqualTo(Integer value) {
            addCriterion("grade_min <>", value, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinGreaterThan(Integer value) {
            addCriterion("grade_min >", value, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade_min >=", value, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinLessThan(Integer value) {
            addCriterion("grade_min <", value, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinLessThanOrEqualTo(Integer value) {
            addCriterion("grade_min <=", value, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinIn(List<Integer> values) {
            addCriterion("grade_min in", values, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinNotIn(List<Integer> values) {
            addCriterion("grade_min not in", values, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinBetween(Integer value1, Integer value2) {
            addCriterion("grade_min between", value1, value2, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMinNotBetween(Integer value1, Integer value2) {
            addCriterion("grade_min not between", value1, value2, "gradeMin");
            return (Criteria) this;
        }

        public Criteria andGradeMaxIsNull() {
            addCriterion("grade_max is null");
            return (Criteria) this;
        }

        public Criteria andGradeMaxIsNotNull() {
            addCriterion("grade_max is not null");
            return (Criteria) this;
        }

        public Criteria andGradeMaxEqualTo(Integer value) {
            addCriterion("grade_max =", value, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxNotEqualTo(Integer value) {
            addCriterion("grade_max <>", value, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxGreaterThan(Integer value) {
            addCriterion("grade_max >", value, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade_max >=", value, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxLessThan(Integer value) {
            addCriterion("grade_max <", value, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxLessThanOrEqualTo(Integer value) {
            addCriterion("grade_max <=", value, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxIn(List<Integer> values) {
            addCriterion("grade_max in", values, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxNotIn(List<Integer> values) {
            addCriterion("grade_max not in", values, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxBetween(Integer value1, Integer value2) {
            addCriterion("grade_max between", value1, value2, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andGradeMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("grade_max not between", value1, value2, "gradeMax");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNull() {
            addCriterion("region_name is null");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNotNull() {
            addCriterion("region_name is not null");
            return (Criteria) this;
        }

        public Criteria andRegionNameEqualTo(String value) {
            addCriterion("region_name =", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotEqualTo(String value) {
            addCriterion("region_name <>", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThan(String value) {
            addCriterion("region_name >", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThanOrEqualTo(String value) {
            addCriterion("region_name >=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThan(String value) {
            addCriterion("region_name <", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThanOrEqualTo(String value) {
            addCriterion("region_name <=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLike(String value) {
            addCriterion("region_name like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotLike(String value) {
            addCriterion("region_name not like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameIn(List<String> values) {
            addCriterion("region_name in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotIn(List<String> values) {
            addCriterion("region_name not in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameBetween(String value1, String value2) {
            addCriterion("region_name between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotBetween(String value1, String value2) {
            addCriterion("region_name not between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andConsumeMinIsNull() {
            addCriterion("consume_min is null");
            return (Criteria) this;
        }

        public Criteria andConsumeMinIsNotNull() {
            addCriterion("consume_min is not null");
            return (Criteria) this;
        }

        public Criteria andConsumeMinEqualTo(BigDecimal value) {
            addCriterion("consume_min =", value, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinNotEqualTo(BigDecimal value) {
            addCriterion("consume_min <>", value, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinGreaterThan(BigDecimal value) {
            addCriterion("consume_min >", value, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("consume_min >=", value, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinLessThan(BigDecimal value) {
            addCriterion("consume_min <", value, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("consume_min <=", value, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinIn(List<BigDecimal> values) {
            addCriterion("consume_min in", values, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinNotIn(List<BigDecimal> values) {
            addCriterion("consume_min not in", values, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consume_min between", value1, value2, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consume_min not between", value1, value2, "consumeMin");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxIsNull() {
            addCriterion("consume_max is null");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxIsNotNull() {
            addCriterion("consume_max is not null");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxEqualTo(BigDecimal value) {
            addCriterion("consume_max =", value, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxNotEqualTo(BigDecimal value) {
            addCriterion("consume_max <>", value, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxGreaterThan(BigDecimal value) {
            addCriterion("consume_max >", value, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("consume_max >=", value, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxLessThan(BigDecimal value) {
            addCriterion("consume_max <", value, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("consume_max <=", value, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxIn(List<BigDecimal> values) {
            addCriterion("consume_max in", values, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxNotIn(List<BigDecimal> values) {
            addCriterion("consume_max not in", values, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consume_max between", value1, value2, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andConsumeMaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consume_max not between", value1, value2, "consumeMax");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterionForJDBCDate("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterionForJDBCDate("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andLimitIsNull() {
            addCriterion("limit is null");
            return (Criteria) this;
        }

        public Criteria andLimitIsNotNull() {
            addCriterion("limit is not null");
            return (Criteria) this;
        }

        public Criteria andLimitEqualTo(Integer value) {
            addCriterion("limit =", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotEqualTo(Integer value) {
            addCriterion("limit <>", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitGreaterThan(Integer value) {
            addCriterion("limit >", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("limit >=", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitLessThan(Integer value) {
            addCriterion("limit <", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitLessThanOrEqualTo(Integer value) {
            addCriterion("limit <=", value, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitIn(List<Integer> values) {
            addCriterion("limit in", values, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotIn(List<Integer> values) {
            addCriterion("limit not in", values, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitBetween(Integer value1, Integer value2) {
            addCriterion("limit between", value1, value2, "limit");
            return (Criteria) this;
        }

        public Criteria andLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("limit not between", value1, value2, "limit");
            return (Criteria) this;
        }

        public Criteria andJoinIsNull() {
            addCriterion("join is null");
            return (Criteria) this;
        }

        public Criteria andJoinIsNotNull() {
            addCriterion("join is not null");
            return (Criteria) this;
        }

        public Criteria andJoinEqualTo(Integer value) {
            addCriterion("join =", value, "join");
            return (Criteria) this;
        }

        public Criteria andJoinNotEqualTo(Integer value) {
            addCriterion("join <>", value, "join");
            return (Criteria) this;
        }

        public Criteria andJoinGreaterThan(Integer value) {
            addCriterion("join >", value, "join");
            return (Criteria) this;
        }

        public Criteria andJoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("join >=", value, "join");
            return (Criteria) this;
        }

        public Criteria andJoinLessThan(Integer value) {
            addCriterion("join <", value, "join");
            return (Criteria) this;
        }

        public Criteria andJoinLessThanOrEqualTo(Integer value) {
            addCriterion("join <=", value, "join");
            return (Criteria) this;
        }

        public Criteria andJoinIn(List<Integer> values) {
            addCriterion("join in", values, "join");
            return (Criteria) this;
        }

        public Criteria andJoinNotIn(List<Integer> values) {
            addCriterion("join not in", values, "join");
            return (Criteria) this;
        }

        public Criteria andJoinBetween(Integer value1, Integer value2) {
            addCriterion("join between", value1, value2, "join");
            return (Criteria) this;
        }

        public Criteria andJoinNotBetween(Integer value1, Integer value2) {
            addCriterion("join not between", value1, value2, "join");
            return (Criteria) this;
        }

        public Criteria andUseMixIsNull() {
            addCriterion("use_mix is null");
            return (Criteria) this;
        }

        public Criteria andUseMixIsNotNull() {
            addCriterion("use_mix is not null");
            return (Criteria) this;
        }

        public Criteria andUseMixEqualTo(String value) {
            addCriterion("use_mix =", value, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixNotEqualTo(String value) {
            addCriterion("use_mix <>", value, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixGreaterThan(String value) {
            addCriterion("use_mix >", value, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixGreaterThanOrEqualTo(String value) {
            addCriterion("use_mix >=", value, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixLessThan(String value) {
            addCriterion("use_mix <", value, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixLessThanOrEqualTo(String value) {
            addCriterion("use_mix <=", value, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixLike(String value) {
            addCriterion("use_mix like", value, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixNotLike(String value) {
            addCriterion("use_mix not like", value, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixIn(List<String> values) {
            addCriterion("use_mix in", values, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixNotIn(List<String> values) {
            addCriterion("use_mix not in", values, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixBetween(String value1, String value2) {
            addCriterion("use_mix between", value1, value2, "useMix");
            return (Criteria) this;
        }

        public Criteria andUseMixNotBetween(String value1, String value2) {
            addCriterion("use_mix not between", value1, value2, "useMix");
            return (Criteria) this;
        }

        public Criteria andUserLimitIsNull() {
            addCriterion("user_limit is null");
            return (Criteria) this;
        }

        public Criteria andUserLimitIsNotNull() {
            addCriterion("user_limit is not null");
            return (Criteria) this;
        }

        public Criteria andUserLimitEqualTo(Integer value) {
            addCriterion("user_limit =", value, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitNotEqualTo(Integer value) {
            addCriterion("user_limit <>", value, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitGreaterThan(Integer value) {
            addCriterion("user_limit >", value, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_limit >=", value, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitLessThan(Integer value) {
            addCriterion("user_limit <", value, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitLessThanOrEqualTo(Integer value) {
            addCriterion("user_limit <=", value, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitIn(List<Integer> values) {
            addCriterion("user_limit in", values, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitNotIn(List<Integer> values) {
            addCriterion("user_limit not in", values, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitBetween(Integer value1, Integer value2) {
            addCriterion("user_limit between", value1, value2, "userLimit");
            return (Criteria) this;
        }

        public Criteria andUserLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("user_limit not between", value1, value2, "userLimit");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andForNewIsNull() {
            addCriterion("for_new is null");
            return (Criteria) this;
        }

        public Criteria andForNewIsNotNull() {
            addCriterion("for_new is not null");
            return (Criteria) this;
        }

        public Criteria andForNewEqualTo(String value) {
            addCriterion("for_new =", value, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewNotEqualTo(String value) {
            addCriterion("for_new <>", value, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewGreaterThan(String value) {
            addCriterion("for_new >", value, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewGreaterThanOrEqualTo(String value) {
            addCriterion("for_new >=", value, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewLessThan(String value) {
            addCriterion("for_new <", value, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewLessThanOrEqualTo(String value) {
            addCriterion("for_new <=", value, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewLike(String value) {
            addCriterion("for_new like", value, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewNotLike(String value) {
            addCriterion("for_new not like", value, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewIn(List<String> values) {
            addCriterion("for_new in", values, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewNotIn(List<String> values) {
            addCriterion("for_new not in", values, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewBetween(String value1, String value2) {
            addCriterion("for_new between", value1, value2, "forNew");
            return (Criteria) this;
        }

        public Criteria andForNewNotBetween(String value1, String value2) {
            addCriterion("for_new not between", value1, value2, "forNew");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_discount
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 10 11:13:53 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_discount
     *
     * @mbggenerated Wed Jun 10 11:13:53 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
