package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.GoodsType;
import com.dunbian.jujiabao.appobj.extend.GoodsTypeAO;
import com.dunbian.jujiabao.appobj.generator.GoodsTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int countByExample(GoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int deleteByExample(GoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int insert(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int insertSelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    List<GoodsTypeAO> selectByExample(GoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
	GoodsTypeAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") GoodsType record, @Param("example") GoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int updateByExample(@Param("record") GoodsType record, @Param("example") GoodsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated Tue Mar 31 11:04:41 CST 2015
     */
    int updateByPrimaryKey(GoodsType record);
}
