package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.DiscountRecord;
import com.dunbian.jujiabao.appobj.extend.DiscountRecordAO;
import com.dunbian.jujiabao.appobj.generator.DiscountRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiscountRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int countByExample(DiscountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int deleteByExample(DiscountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int insert(DiscountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int insertSelective(DiscountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    List<DiscountRecordAO> selectByExample(DiscountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
	DiscountRecordAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") DiscountRecord record, @Param("example") DiscountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int updateByExample(@Param("record") DiscountRecord record, @Param("example") DiscountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int updateByPrimaryKeySelective(DiscountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discount_record
     *
     * @mbggenerated Sat Mar 21 16:19:54 CST 2015
     */
    int updateByPrimaryKey(DiscountRecord record);
}
