package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.AccountDetail;
import com.dunbian.jujiabao.appobj.extend.AccountDetailAO;
import com.dunbian.jujiabao.appobj.generator.AccountDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int countByExample(AccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int deleteByExample(AccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int insert(AccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int insertSelective(AccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    List<AccountDetailAO> selectByExample(AccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
	AccountDetailAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") AccountDetail record, @Param("example") AccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int updateByExample(@Param("record") AccountDetail record, @Param("example") AccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int updateByPrimaryKeySelective(AccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_detail
     *
     * @mbggenerated Tue Jun 02 15:17:48 CST 2015
     */
    int updateByPrimaryKey(AccountDetail record);
}
