package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.AdvertisementShow;
import com.dunbian.jujiabao.appobj.extend.AdvertisementShowAO;
import com.dunbian.jujiabao.appobj.generator.AdvertisementShowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvertisementShowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int countByExample(AdvertisementShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int deleteByExample(AdvertisementShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int insert(AdvertisementShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int insertSelective(AdvertisementShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    List<AdvertisementShowAO> selectByExample(AdvertisementShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
	AdvertisementShowAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") AdvertisementShow record, @Param("example") AdvertisementShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int updateByExample(@Param("record") AdvertisementShow record, @Param("example") AdvertisementShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int updateByPrimaryKeySelective(AdvertisementShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement_show
     *
     * @mbggenerated Mon Mar 23 15:10:34 CST 2015
     */
    int updateByPrimaryKey(AdvertisementShow record);
}
