package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.FoodWeek;
import com.dunbian.jujiabao.appobj.extend.FoodWeekAO;
import com.dunbian.jujiabao.appobj.generator.FoodWeekExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int countByExample(FoodWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int deleteByExample(FoodWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int insert(FoodWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int insertSelective(FoodWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    List<FoodWeekAO> selectByExample(FoodWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
	FoodWeekAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") FoodWeek record, @Param("example") FoodWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int updateByExample(@Param("record") FoodWeek record, @Param("example") FoodWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int updateByPrimaryKeySelective(FoodWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_week
     *
     * @mbggenerated Tue Mar 31 10:43:03 CST 2015
     */
    int updateByPrimaryKey(FoodWeek record);
}
