package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.FoodType;
import com.dunbian.jujiabao.appobj.extend.FoodTypeAO;
import com.dunbian.jujiabao.appobj.generator.FoodTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int countByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int deleteByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int insert(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int insertSelective(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    List<FoodTypeAO> selectByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
	FoodTypeAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") FoodType record, @Param("example") FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int updateByExample(@Param("record") FoodType record, @Param("example") FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int updateByPrimaryKeySelective(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food_type
     *
     * @mbggenerated Wed Apr 01 10:05:50 CST 2015
     */
    int updateByPrimaryKey(FoodType record);
}
