package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.ManageUser;
import com.dunbian.jujiabao.appobj.extend.ManageUserAO;
import com.dunbian.jujiabao.appobj.generator.ManageUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManageUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int countByExample(ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int deleteByExample(ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int insert(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int insertSelective(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    List<ManageUserAO> selectByExample(ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
	ManageUserAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ManageUser record, @Param("example") ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int updateByExample(@Param("record") ManageUser record, @Param("example") ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int updateByPrimaryKeySelective(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manage_user
     *
     * @mbggenerated Thu Feb 26 22:52:01 CST 2015
     */
    int updateByPrimaryKey(ManageUser record);
}
