package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.RechargeSet;
import com.dunbian.jujiabao.appobj.extend.RechargeSetAO;
import com.dunbian.jujiabao.appobj.generator.RechargeSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int countByExample(RechargeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int deleteByExample(RechargeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int insert(RechargeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int insertSelective(RechargeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    List<RechargeSetAO> selectByExample(RechargeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
	RechargeSetAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int updateByExampleSelective(@Param("record") RechargeSet record, @Param("example") RechargeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int updateByExample(@Param("record") RechargeSet record, @Param("example") RechargeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int updateByPrimaryKeySelective(RechargeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_set
     *
     * @mbggenerated Sat Apr 11 10:24:16 CST 2015
     */
    int updateByPrimaryKey(RechargeSet record);
}
