package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.RechargeRecord;
import com.dunbian.jujiabao.appobj.extend.RechargeRecordAO;
import com.dunbian.jujiabao.appobj.generator.RechargeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int countByExample(RechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int deleteByExample(RechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int insert(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int insertSelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    List<RechargeRecordAO> selectByExample(RechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
	RechargeRecordAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int updateByExampleSelective(@Param("record") RechargeRecord record, @Param("example") RechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int updateByExample(@Param("record") RechargeRecord record, @Param("example") RechargeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int updateByPrimaryKeySelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge_record
     *
     * @mbggenerated Tue Apr 14 16:21:49 CST 2015
     */
    int updateByPrimaryKey(RechargeRecord record);
}
