package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.Seckill;
import com.dunbian.jujiabao.appobj.extend.SeckillAO;
import com.dunbian.jujiabao.appobj.generator.SeckillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int countByExample(SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int deleteByExample(SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int insert(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int insertSelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    List<SeckillAO> selectByExample(SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
	SeckillAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") Seckill record, @Param("example") SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int updateByExample(@Param("record") Seckill record, @Param("example") SeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int updateByPrimaryKeySelective(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Mon Apr 06 15:07:45 CST 2015
     */
    int updateByPrimaryKey(Seckill record);
}
