package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.SetDetail;
import com.dunbian.jujiabao.appobj.extend.SetDetailAO;
import com.dunbian.jujiabao.appobj.generator.SetDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SetDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int countByExample(SetDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int deleteByExample(SetDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int insert(SetDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int insertSelective(SetDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    List<SetDetailAO> selectByExample(SetDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
	SetDetailAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") SetDetail record, @Param("example") SetDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByExample(@Param("record") SetDetail record, @Param("example") SetDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByPrimaryKeySelective(SetDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_set_detail
     *
     * @mbggenerated Sun Feb 08 11:00:03 CST 2015
     */
    int updateByPrimaryKey(SetDetail record);
}
