package com.dunbian.jujiabao.db.generator;

import com.dunbian.jujiabao.appobj.generator.Sms;
import com.dunbian.jujiabao.appobj.extend.SmsAO;
import com.dunbian.jujiabao.appobj.generator.SmsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int countByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int deleteByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int insert(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int insertSelective(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    List<SmsAO> selectByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
	SmsAO selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int updateByExampleSelective(@Param("record") Sms record, @Param("example") SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int updateByExample(@Param("record") Sms record, @Param("example") SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int updateByPrimaryKeySelective(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Sun Jan 25 09:34:42 CST 2015
     */
    int updateByPrimaryKey(Sms record);
}
